### ISSUE TITLE
excuse me ,please help me ?

### ISSUE THREAD

**Issue by zhangbuding** [VctrySam/do-app#4]
hello, 
i want to study RN from your project ,
but when i execute  `react-native run-ios`,its wrong, 
like this 👇
`The following build commands failed:
	CompileC /Users/Cy/Desktop/myBranch/do_2/ios/Build/Intermediates/RNVectorIcons.build/Debug-iphonesimulator/RNVectorIcons.build/Objects-normal/x86_64/RNVectorIconsManager.o RNVectorIconsManager/RNVectorIconsManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/Cy/Desktop/myBranch/do_2/ios/Build/Intermediates/RCTImage.build/Debug-iphonesimulator/RCTImage.build/Objects-normal/x86_64/RCTVirtualImageManager.o RCTVirtualImageManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Installing build/Build/Products/Debug-iphonesimulator/do_2.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/Cy/Desktop/myBranch/do_2/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/do_2.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:574:11)
    at Object.execFileSync (child_process.js:592:13)
    at _runIOS (/Users/Cy/Desktop/myBranch/do_2/node_modules/react-native/local-cli/runIOS/runIOS.js:77:34)
    at /Users/Cy/Desktop/myBranch/do_2/node_modules/react-native/local-cli/runIOS/runIOS.js:24:5
    at tryCallTwo (/Users/Cy/Desktop/myBranch/do_2/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/Cy/Desktop/myBranch/do_2/node_modules/promise/lib/core.js:200:13)
    at new Promise (/Users/Cy/Desktop/myBranch/do_2/node_modules/promise/lib/core.js:66:3)
    at Array.runIOS (/Users/Cy/Desktop/myBranch/do_2/node_modules/react-native/local-cli/runIOS/runIOS.js:23:10)
    at Object.run (/Users/Cy/Desktop/myBranch/do_2/node_modules/react-native/local-cli/cli.js:86:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:117:7)
`

**Comment by zhangbuding** [comment]
could you help me ? thank you so much : )

**Comment by zhangbuding** [comment]
oh... now error is 👇, :  (


> Error building DependencyGraph:
 Error: Naming collision detected: /Users/Cy/Desktop/do-app/node_modules/prop-types/node_modules/fbjs/package.json collides with /Users/Cy/Desktop/do-app/node_modules/create-react-class/node_modules/fbjs/package.json
    at HasteMap._updateHasteMap (/Users/Cy/Desktop/do-app/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:132:13)
    at /Users/Cy/Desktop/do-app/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/HasteMap.js:112:32
    at tryCallOne (/Users/Cy/Desktop/do-app/node_modules/promise/lib/core.js:37:12)
    at /Users/Cy/Desktop/do-app/node_modules/promise/lib/core.js:123:15
    at flush (/Users/Cy/Desktop/do-app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
